---
title: "High School Performance and Future Salary, by College"
description: |
  This project analyzes a small subset of colleges in the US in order to establish a correlation between the performance of the undergraduates of these colleges in high school, and their mid-career median salary. As you can see, the trend is mostly positive.
site: distill::distill_website
---

```{r setup, layout = "l-body-outset", include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggthemes)
library(knitr)
library(rmarkdown)
library(gt)
library(plotly)
library(dplyr)

college_data <- read_csv("rawdata/College_Data.csv")
salary_by_degree <- read_csv("rawdata/degrees-that-pay-back.csv")
salary_by_college <- read_csv("rawdata/salaries-by-college-type.csv")
salary_by_region <- read_csv("rawdata/salaries-by-region.csv")
```

```{r, cleaning}
college_data_clean <- college_data %>%
  rename(college = X1) %>%
  select(college, Top10perc)

salary_by_region_clean <- salary_by_region %>%
  select("School Name", "Mid-Career Median Salary")
# paged_table(salary_by_region_clean)

salary_by_college_clean <- salary_by_college %>%
  select("School Name", "Mid-Career Median Salary")
# paged_table(salary_by_college_clean)

salary_by_college_full <- left_join(salary_by_region_clean, salary_by_college_clean, by = "School Name") %>%
  select("School Name", "Mid-Career Median Salary.x") %>%
  rename(college = "School Name", median_salary_mid_career = "Mid-Career Median Salary.x") %>%
  drop_na()

college_top10_salary <- left_join(college_data_clean, salary_by_college_full, by = "college") %>%
  drop_na() %>%
  arrange(desc(Top10perc))

college_top10_salary$median_salary_mid_career <- as.numeric(gsub('[$,]', '', college_top10_salary$median_salary_mid_career))

college_top10_salary_gpa <- college_top10_salary %>%
  slice(-c(71, 82, 84)) %>%
  add_column(avg_gpa = c(3.96, 3.95, 3.94, 4.04, 3.87, 3.95, 3.94, 3.95, 3.92, 3.90, 3.91, 3.94, 3.86, 3.91, 3.91, 3.90, 3.93, 3.80, 3.90, 3.86, 3.89, 3.76, 3.82, 3.87, 3.40, 3.86, 3.89, 3.80, 3.60, 3.92, 3.85, 3.50, 3.75, 3.57, 3.54, 3.74, 3.90, 3.50, 3.64, 3.81, 3.59, 3.74, 3.65, 3.40, 3.40, 3.80, 3.87, 3.81, 4.18, 3.30, 3.66, 3.74, 3.46, 3.63, 3.49, 3.74, 3.60, 3.59, 3.73, 3.69, 3.59, 3.86, 3.42, 3.62, 3.53, 3.58, 3.60, 3.55, 3.60, 3.50, 3.51, 3.76, 3.50, 3.60, 3.50, 3.40, 3.60, 3.54, 3.50, 3.29, 3.42, 3.57, 4.05, 3.37, 3.48, 3.30, 3.66, 3.50, 3.21, 3.91, 3.30, 3.60, 3.30, 3.00, 3.10, 3.67, 3.36, 3.21, 3.23, 2.70, 3.34, 2.99))
# Data acquired from collegesimply.com, which got its data from Wintergreen Orchard House and IPEDS; and also from prepscholar.com

college_top10_salary_gpa_plot <- college_top10_salary_gpa %>%
  ggplot(mapping = aes(x = Top10perc,
                       y = median_salary_mid_career,
                       text = college)) +
    geom_point() +
    labs(title = "High School Performance and Predicted Future Salary, by College",
         x = "Percent of students who were in the top 10% of students at their high school",
         y = "Mid-Career Median Salary")
ggplotly(college_top10_salary_gpa_plot)

# This plotly plot is a for top10perc and salary, make another one by avg_gpa and salary! Also add some color to this graph its ugly af
```